# your domain
domain: pachongdalao.herokuapp.com

# database url
database_url: "test.pachongdalao.herokuapp.com"

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://example.com/source.yaml