# your domain
domain: pachongfree.herokuapp.com

# database url
database_url: "test.pachongfree.herokuapp.com"

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://pachongfree.herokuapp.com/source.yaml